// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsFR3CC6_VjmBVjV9n8vBd8guNboQIRs',
    appId: '1:581335919406:web:f4a2f23bdcb8e01100e8bf',
    messagingSenderId: '581335919406',
    projectId: 'healwell-c6d4e',
    authDomain: 'healwell-c6d4e.firebaseapp.com',
    storageBucket: 'healwell-c6d4e.appspot.com',
    measurementId: 'G-3VZ4XM5SKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkDt7-QZcwEuIZpLAFN1DtB0NvZGkAb4',
    appId: '1:581335919406:android:f1116fe6108d164100e8bf',
    messagingSenderId: '581335919406',
    projectId: 'healwell-c6d4e',
    storageBucket: 'healwell-c6d4e.appspot.com',
  );
}
